name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest #python:3.9-slim-buster 
    container:
      image: python:3.9-slim-buster
      options: --user root

    steps:
    - name: Install dependencies
      run: apt-get update && apt-get install -y python3 make git

    - name: Run tests
      run: make test 
